version: '3.2'

services:
  ckan:
    image: viderum/ckan-cloud-docker:ckan-latest-datagov-theme
    build:
      args:
        POST_INSTALL: |
          install_standard_ckan_extension_github ckan/ckanext-spatial ckanext-spatial &&\
          install_standard_ckan_extension_github ckan/ckanext-xloader ckanext-xloader &&\
          install_standard_ckan_extension_github datagovuk/ckanext-report ckanext-report &&\
          install_standard_ckan_extension_github ckan/ckanext-archiver ckanext-archiver &&\
          install_standard_ckan_extension_github ckan/ckanext-harvest ckanext-harvest &&\
          install_standard_ckan_extension_github ckan/ckanext-dcat ckanext-dcat &&\
          install_standard_ckan_extension_github GSA/ckanext-datajson ckanext-datajson &&\
          install_standard_ckan_extension_github GSA/ckanext-geodatagov ckanext-geodatagov
        POST_DOCKER_BUILD: |
          mkdir -p /var/tmp/ckan/dynamic_menu
        CKAN_INIT: |
          ckan-paster --plugin=ckanext-archiver archiver init  -c "CKAN_CONFIG/production.ini"
          ckan-paster --plugin=ckanext-report report initdb  -c "CKAN_CONFIG/production.ini"
          ckan-paster --plugin=ckanext-harvest harvester initdb  -c "CKAN_CONFIG/production.ini"
    environment:
    - CKAN_CONFIG_TEMPLATE_PREFIX=datagov-theme-
  jobs:
    image: viderum/ckan-cloud-docker:ckan-latest-datagov-theme
    environment:
    - CKAN_CONFIG_TEMPLATE_PREFIX=datagov-theme-

  db:
    image: mdillon/postgis
    build:
      args:
        DB_INIT: |
          psql --dbname="ckan" -c "CREATE EXTENSION IF NOT EXISTS postgis;                  \
                                   CREATE EXTENSION IF NOT EXISTS postgis_topology;         \
                                   CREATE EXTENSION IF NOT EXISTS fuzzystrmatch;            \
                                   CREATE EXTENSION IF NOT EXISTS postgis_tiger_geocoder;"
