version: '3.2'

services:

  db:
    image: viderum/ckan-cloud-docker:db-latest
    build:
      context: db
    restart: always
    ports:
    - "127.0.0.1:5432:5432"
    environment:
    - POSTGRES_PASSWORD=123456
    volumes:
    - db:/var/lib/postgresql/data
    networks:
    - ckan-multi

  jobs-db:
    image: postgres
    restart: always
    ports:
    - "127.0.0.1:5433:5432"
    environment:
    - POSTGRES_PASSWORD=123456
    volumes:
    - jobs-db:/var/lib/postgresql/data
    networks:
    - ckan-multi

  datastore-db:
    image: viderum/ckan-cloud-docker:db-latest
    restart: always
    ports:
    - "127.0.0.1:5434:5432"
    environment:
    - POSTGRES_PASSWORD=123456
    - DATASTORE_RO_PASSWORD=123456
    - DATASTORE_RO_USER=readonly
    - DATASTORE_PUBLIC_RO_PASSWORD=123456
    volumes:
    - datastore-db:/var/lib/postgresql/data
    networks:
    - ckan-multi

  ckan:
    depends_on:
    - db
    - jobs-db
    - datastore-db

volumes:
  db:
  jobs-db:
  datastore-db:
